// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Dx5pTvQVUblhKn6z4mHWz6cx-ZbqGK0',
    appId: '1:657625155783:web:7aac74a93c48d62ac096e2',
    messagingSenderId: '657625155783',
    projectId: 'parikshit-test-project',
    authDomain: 'parikshit-test-project.firebaseapp.com',
    storageBucket: 'parikshit-test-project.appspot.com',
    measurementId: 'G-YZL9PL77W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEeFCRf7xN6yDgOoFldlr90ybTXjkRviM',
    appId: '1:657625155783:android:cd518e39569435f2c096e2',
    messagingSenderId: '657625155783',
    projectId: 'parikshit-test-project',
    storageBucket: 'parikshit-test-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKpM-Jd7j9YVCYQQU2c4Bgo-8F2Ys3HDw',
    appId: '1:657625155783:ios:8f7ef9e500110a69c096e2',
    messagingSenderId: '657625155783',
    projectId: 'parikshit-test-project',
    storageBucket: 'parikshit-test-project.appspot.com',
    iosClientId: '657625155783-g684le8p5inpffoq9nscv49ltms5rpou.apps.googleusercontent.com',
    iosBundleId: 'com.example.agendaboaassignmentparikshit',
  );
}
